"""HTTP API for the Telegram Mini App.

Provides endpoints for the Mini App to read the settings registry,
read/write per-user overrides, and apply presets. Uses aiohttp.

Authentication is via ephemeral Bearer tokens generated by the /webapp
bot command. Tokens have a 30-minute sliding TTL.
"""

import asyncio
import json
import secrets
import shutil
import tempfile
import time
import zipfile
from pathlib import Path

from aiohttp import web

from .config import Config
from .file_utils import find_models_in_zip
from .presets import load_presets
from .settings_eval import build_dep_graph, build_reverse_deps, evaluate_expressions
from .settings_registry import SettingDefinition
from .settings_validate import validate
from .packing import pack_models
from .slicer import _resolve_rotation, _resolve_scale, resolve_settings, slice_batch, slice_file
from .stl_transform import needs_rotation, needs_scaling, scale_stl
from .threemf import convert_3mf_to_stl

TOKEN_TTL = 1800  # 30-minute sliding window
TOKEN_MAX_TTL = 86400  # 24-hour absolute maximum


def generate_token() -> str:
    """Generate a cryptographically random URL-safe token."""
    return secrets.token_urlsafe(32)


def validate_token(tokens: dict, token_str: str) -> int | None:
    """Validate a Bearer token. Returns user_id or None if invalid/expired."""
    entry = tokens.get(token_str)
    if entry is None:
        return None
    user_id, expiry, created = entry
    now = time.time()
    if now > expiry or now > created + TOKEN_MAX_TTL:
        del tokens[token_str]
        return None
    # Refresh sliding TTL (created stays the same)
    tokens[token_str] = (user_id, time.time() + TOKEN_TTL, created)
    return user_id


def cleanup_expired(tokens: dict) -> None:
    """Remove all expired tokens from the dict."""
    now = time.time()
    expired = [
        k for k, (_, expiry, created) in tokens.items()
        if now > expiry or now > created + TOKEN_MAX_TTL
    ]
    for k in expired:
        del tokens[k]


def _setting_to_dict(defn: SettingDefinition) -> dict:
    """Serialize a SettingDefinition to a JSON-friendly dict."""
    d = {
        "key": defn.key,
        "label": defn.label,
        "description": defn.description,
        "type": defn.setting_type,
        "default_value": defn.default_value,
        "category": defn.category,
    }
    if defn.unit:
        d["unit"] = defn.unit
    if defn.minimum_value is not None:
        d["minimum_value"] = defn.minimum_value
    if defn.maximum_value is not None:
        d["maximum_value"] = defn.maximum_value
    if defn.minimum_value_warning is not None:
        d["minimum_value_warning"] = defn.minimum_value_warning
    if defn.maximum_value_warning is not None:
        d["maximum_value_warning"] = defn.maximum_value_warning
    if defn.options:
        d["options"] = defn.options
    if defn.value_expression is not None:
        d["value_expression"] = defn.value_expression
    return d


def _build_registry_response(config: Config) -> dict:
    """Build the full registry response: settings grouped by category, presets, defaults."""
    all_settings = config.registry.all_settings()

    # Group settings by category
    categories: dict[str, list[dict]] = {}
    settings_list = []
    for key, defn in all_settings.items():
        sd = _setting_to_dict(defn)
        if key in config.defaults:
            sd.pop("value_expression", None)
        settings_list.append(sd)
        cat = defn.category or "Other"
        categories.setdefault(cat, []).append(sd)

    presets = load_presets()
    preset_data = {
        name: {"description": p["description"], "settings": p["settings"]}
        for name, p in presets.items()
    }

    dep_graph = build_dep_graph(config.registry)
    reverse = build_reverse_deps(dep_graph)
    # Convert sets to sorted lists for JSON serialization
    reverse_json = {k: sorted(v) for k, v in reverse.items()}

    return {
        "settings": settings_list,
        "categories": categories,
        "presets": preset_data,
        "defaults": config.defaults,
        "reverse_deps": reverse_json,
    }


def _validate_overrides(config: Config, overrides: dict[str, str]) -> dict:
    """Validate a batch of key:value pairs against the registry.

    Returns {"applied": {key: value}, "errors": {key: msg}, "warnings": {key: msg}}.
    """
    applied = {}
    errors = {}
    warnings = {}

    for key, raw_value in overrides.items():
        defn = config.registry.get(key)
        if not defn:
            errors[key] = f"Unknown setting: '{key}'"
            continue
        result = validate(defn, str(raw_value))
        if not result.ok:
            errors[key] = result.error
        else:
            applied[key] = result.coerced_value
            if result.warning:
                warnings[key] = result.warning

    return {"applied": applied, "errors": errors, "warnings": warnings}


async def handle_registry(request: web.Request) -> web.Response:
    """GET /api/registry — return the full settings registry."""
    config: Config = request.app["config"]

    # Use cached response if available
    cached = request.app.get("_registry_cache")
    if cached is None:
        cached = json.dumps(_build_registry_response(config))
        request.app["_registry_cache"] = cached

    return web.Response(text=cached, content_type="application/json")


async def handle_get_settings(request: web.Request) -> web.Response:
    """GET /api/settings — return current user overrides."""
    user_id = request["user_id"]
    user_settings: dict = request.app["user_settings"]
    overrides = user_settings.get(user_id, {})
    return web.json_response({"overrides": overrides})


async def handle_post_settings(request: web.Request) -> web.Response:
    """POST /api/settings — validate and apply user overrides.

    Body: {"overrides": {"key": "value", ...}, "remove": ["key", ...]}
    """
    user_id = request["user_id"]
    config: Config = request.app["config"]
    user_settings: dict = request.app["user_settings"]

    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError):
        return web.json_response({"error": "invalid JSON body"}, status=400)

    # Validate and apply overrides
    new_overrides = body.get("overrides", {})
    remove_keys = body.get("remove", [])

    result = _validate_overrides(config, new_overrides)

    # Apply valid settings
    if user_id not in user_settings:
        user_settings[user_id] = {}
    user_settings[user_id].update(result["applied"])

    # Remove requested keys
    for key in remove_keys:
        user_settings[user_id].pop(key, None)
    if not user_settings[user_id]:
        user_settings.pop(user_id, None)

    save_fn = request.app.get("save_fn")
    if save_fn:
        save_fn()

    return web.json_response(result)


async def handle_delete_settings(request: web.Request) -> web.Response:
    """DELETE /api/settings — clear all overrides for the authenticated user."""
    user_id = request["user_id"]
    user_settings: dict = request.app["user_settings"]
    user_settings.pop(user_id, None)

    save_fn = request.app.get("save_fn")
    if save_fn:
        save_fn()

    return web.json_response({"overrides": {}})


async def handle_get_starred(request: web.Request) -> web.Response:
    """GET /api/starred — return the current starred keys."""
    starred: set = request.app.get("starred_keys", set())
    return web.json_response({"keys": sorted(starred)})


async def handle_post_starred(request: web.Request) -> web.Response:
    """POST /api/starred — add/remove starred keys (auth required).

    Body: {"add": [...], "remove": [...]}
    """
    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError):
        return web.json_response({"error": "invalid JSON body"}, status=400)

    starred: set = request.app.get("starred_keys", set())
    starred.update(body.get("add", []))
    starred.difference_update(body.get("remove", []))

    save_fn = request.app.get("save_starred_fn")
    if save_fn:
        save_fn()

    return web.json_response({"keys": sorted(starred)})


async def handle_evaluate(request: web.Request) -> web.Response:
    """POST /api/evaluate — compute all expression-based settings.

    Body: {"overrides": {"key": "value", ...}}
    """
    config: Config = request.app["config"]

    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError):
        return web.json_response({"error": "invalid JSON body"}, status=400)

    overrides = body.get("overrides", {})
    pinned = {**config.defaults, **overrides}
    result = evaluate_expressions(config.registry, pinned, config.defaults)

    return web.json_response({
        "computed": result.values,
        "errors": result.errors,
    })


UPLOAD_TTL = 1800  # 30 minutes
ALLOWED_EXTENSIONS = {".stl", ".3mf", ".zip"}
MAX_UPLOAD_SIZE = 100 * 1024 * 1024  # 100 MB


def _cleanup_uploads(uploads: dict) -> None:
    """Remove uploads older than UPLOAD_TTL and delete their temp dirs."""
    now = time.time()
    expired = [fid for fid, info in uploads.items() if now - info["created"] > UPLOAD_TTL]
    for fid in expired:
        tmpdir = uploads.pop(fid).get("tmpdir")
        if tmpdir:
            shutil.rmtree(tmpdir, ignore_errors=True)


def _prepare_stl(original: Path, tmpdir: Path, out_name: str | None = None) -> Path:
    """Convert 3MF to STL if needed, or return the original STL path."""
    if original.suffix.lower() == ".3mf":
        stem = Path(out_name).stem if out_name else original.stem
        stl_path = tmpdir / f"{stem}.stl"
        convert_3mf_to_stl(original, stl_path)
        return stl_path
    return original


async def handle_upload(request: web.Request) -> web.Response:
    """POST /api/upload — accept model file, convert if needed, return file_id."""
    user_id = request["user_id"]
    uploads: dict = request.app["uploads"]
    _cleanup_uploads(uploads)

    reader = await request.multipart()
    field = await reader.next()
    if field is None or field.name != "file":
        return web.json_response({"error": "missing 'file' field"}, status=400)

    filename = field.filename or "model.stl"
    ext = Path(filename).suffix.lower()
    if ext not in ALLOWED_EXTENSIONS:
        return web.json_response(
            {"error": f"unsupported file type ({ext}). Send STL, 3MF, or ZIP."},
            status=400,
        )

    tmpdir = tempfile.mkdtemp(prefix="slicer_upload_")
    file_path = Path(tmpdir) / filename
    size = 0
    with open(file_path, "wb") as f:
        while True:
            chunk = await field.read_chunk(8192)
            if not chunk:
                break
            size += len(chunk)
            if size > MAX_UPLOAD_SIZE:
                shutil.rmtree(tmpdir, ignore_errors=True)
                return web.json_response({"error": "file too large"}, status=413)
            f.write(chunk)

    try:
        models = await asyncio.to_thread(_resolve_upload, file_path, Path(tmpdir))
    except Exception as e:
        shutil.rmtree(tmpdir, ignore_errors=True)
        return web.json_response({"error": str(e)}, status=400)

    file_id = secrets.token_urlsafe(16)
    uploads[file_id] = {
        "tmpdir": tmpdir,
        "original_path": file_path,
        "models": models,
        "filename": filename,
        "user_id": user_id,
        "created": time.time(),
        "slice_task": None,
        "slice_result": None,
    }

    model_names = [m["name"] for m in models]
    return web.json_response({"file_id": file_id, "filename": filename, "models": model_names})


def _resolve_upload(file_path: Path, tmpdir: Path) -> list[dict]:
    """Resolve an uploaded file to a list of {name, stl_path} dicts."""
    ext = file_path.suffix.lower()
    if ext == ".zip":
        extract_dir = tmpdir / "extracted"
        extract_dir.mkdir()
        with zipfile.ZipFile(file_path) as zf:
            zf.extractall(extract_dir)
        models = find_models_in_zip(extract_dir)
        if not models:
            raise ValueError("no model files found in ZIP")
        # Deduplicate names to avoid collisions in tmpdir
        seen: dict[str, int] = {}
        result = []
        for m in sorted(models):
            name = m.name
            if name in seen:
                seen[name] += 1
                stem = m.stem
                suffix = m.suffix
                name = f"{stem}_{seen[name]}{suffix}"
            else:
                seen[name] = 0
            stl = _prepare_stl(m, tmpdir, out_name=name)
            result.append({"name": m.name, "stl_path": str(stl)})
        return result
    stl = _prepare_stl(file_path, tmpdir)
    return [{"name": file_path.name, "stl_path": str(stl)}]


async def handle_upload_model(request: web.Request) -> web.Response:
    """GET /api/upload/{file_id}/model?index=N — return raw STL binary for three.js."""
    user_id = request["user_id"]
    file_id = request.match_info["file_id"]
    uploads: dict = request.app["uploads"]

    info = uploads.get(file_id)
    if info is None:
        return web.json_response({"error": "upload not found"}, status=404)
    if info["user_id"] != user_id:
        return web.json_response({"error": "forbidden"}, status=403)

    models = info["models"]
    idx = int(request.query.get("index", 0))
    if idx < 0 or idx >= len(models):
        return web.json_response({"error": "invalid model index"}, status=400)

    stl_path = Path(models[idx]["stl_path"])
    if not stl_path.exists():
        return web.json_response({"error": "file expired"}, status=410)

    return web.Response(
        body=stl_path.read_bytes(),
        content_type="application/octet-stream",
        headers={"Content-Disposition": f'attachment; filename="{stl_path.name}"'},
    )


async def handle_upload_pack(request: web.Request) -> web.Response:
    """POST /api/upload/{file_id}/pack — compute bed packing layout for preview."""
    user_id = request["user_id"]
    file_id = request.match_info["file_id"]
    config: Config = request.app["config"]
    uploads: dict = request.app["uploads"]
    user_settings: dict = request.app["user_settings"]

    info = uploads.get(file_id)
    if info is None:
        return web.json_response({"error": "upload not found"}, status=404)
    if info["user_id"] != user_id:
        return web.json_response({"error": "forbidden"}, status=403)

    overrides = user_settings.get(user_id, {})
    all_models = info["models"]

    try:
        body = await request.json() if request.content_length else {}
    except Exception:
        body = {}
    indices = body.get("indices")
    if indices is not None:
        if not all(isinstance(i, int) and 0 <= i < len(all_models) for i in indices):
            return web.json_response({"error": "invalid indices"}, status=400)
    else:
        indices = list(range(len(all_models)))

    if not indices:
        return web.json_response({"beds": []})

    stl_paths = [Path(all_models[i]["stl_path"]) for i in indices]

    try:
        active = resolve_settings(config.registry, config.defaults, overrides, config.forced_keys)
        bed_w = float(active.get("machine_width", "235"))
        bed_d = float(active.get("machine_depth", "235"))
        beds_packed = await asyncio.to_thread(pack_models, stl_paths, bed_w, bed_d, active)
    except Exception as exc:
        print(f"Pack error: {exc}", flush=True)
        return web.json_response({"error": str(exc)}, status=500)

    # Map paths back to model indices
    path_to_idx = {str(Path(all_models[i]["stl_path"])): i for i in indices}
    beds = []
    for bed_models in beds_packed:
        bed = []
        for path, ox, oy in bed_models:
            idx = path_to_idx.get(str(path))
            bed.append({
                "index": idx,
                "name": all_models[idx]["name"] if idx is not None else path.name,
                "offset_x": round(ox, 2),
                "offset_y": round(oy, 2),
            })
        beds.append(bed)

    return web.json_response({"beds": beds, "bed_width": bed_w, "bed_depth": bed_d})


async def handle_upload_slice(request: web.Request) -> web.Response:
    """POST /api/upload/{file_id}/slice — start slicing in background."""
    user_id = request["user_id"]
    file_id = request.match_info["file_id"]
    config: Config = request.app["config"]
    uploads: dict = request.app["uploads"]
    user_settings: dict = request.app["user_settings"]

    info = uploads.get(file_id)
    if info is None:
        return web.json_response({"error": "upload not found"}, status=404)
    if info["user_id"] != user_id:
        return web.json_response({"error": "forbidden"}, status=403)
    task = info.get("slice_task")
    if task is not None and not task.done():
        return web.json_response({"error": "slicing already in progress"}, status=409)
    info["slice_result"] = None

    overrides = user_settings.get(user_id, {})
    all_models = info["models"]

    # Parse optional indices to slice a subset
    try:
        body = await request.json() if request.content_length else {}
    except Exception:
        body = {}
    indices = body.get("indices")
    if indices is not None:
        if not all(isinstance(i, int) and 0 <= i < len(all_models) for i in indices):
            return web.json_response({"error": "invalid indices"}, status=400)
        models = [all_models[i] for i in indices]
    else:
        models = all_models

    if not models:
        return web.json_response({"error": "no models selected"}, status=400)

    # Check if batch mode is enabled
    batch = overrides.get("batch_models", config.defaults.get("batch_models", "false"))
    use_batch = batch.lower() in ("true", "1", "yes") and len(models) > 1

    # Copy selected STLs to a fresh temp dir since slice_file moves files
    slice_dir = tempfile.mkdtemp(prefix="slicer_slice_")
    dst_paths = []
    for m in models:
        src = Path(m["stl_path"])
        dst = Path(slice_dir) / src.name
        shutil.copy2(src, dst)
        dst_paths.append(dst)

    # Use a shared archive folder for multi-model slicing
    archive_folder = None
    if len(models) > 1:
        archive_folder = config.archive_dir / Path(info["filename"]).stem / time.strftime("%Y%m%d_%H%M%S")

    async def _run():
        try:
            if use_batch:
                results = await _run_batch(config, dst_paths, overrides, archive_folder)
            else:
                results = await _run_individual(config, dst_paths, overrides, archive_folder)
            info["slice_result"] = {"results": results}
        except Exception as e:
            info["slice_result"] = {"results": [{
                "name": "unknown",
                "success": False,
                "message": f"System error: {e}",
                "archive_path": None,
                "stats": {},
            }]}
        finally:
            shutil.rmtree(slice_dir, ignore_errors=True)

    info["slice_task"] = asyncio.create_task(_run())
    return web.json_response({"status": "slicing"})


async def _run_individual(config, dst_paths, overrides, archive_folder):
    """Slice each model individually."""
    results = []
    for dst in dst_paths:
        success, message, archive_path, stats = await asyncio.to_thread(
            slice_file, config, dst, overrides,
            **({"archive_folder": archive_folder} if archive_folder else {}),
        )
        results.append({
            "name": dst.name,
            "success": success,
            "message": message,
            "archive_path": str(archive_path) if archive_path else None,
            "stats": stats,
        })
    return results


async def _run_batch(config, dst_paths, overrides, archive_folder):
    """Pack models onto beds and slice each bed."""
    # Apply scaling before packing (packing reads bounding boxes)
    sx, sy, sz = _resolve_scale(config.defaults, overrides)
    if needs_scaling(sx, sy, sz):
        for dst in dst_paths:
            scale_stl(dst, sx, sy, sz)

    active = resolve_settings(config.registry, config.defaults, overrides, config.forced_keys)
    bed_w = float(active.get("machine_width", "235"))
    bed_d = float(active.get("machine_depth", "235"))

    beds = pack_models(dst_paths, bed_w, bed_d, active)

    results = []
    for bed_models in beds:
        names = [p.name for p, _, _ in bed_models]
        success, message, archive_path, stats = await asyncio.to_thread(
            slice_batch, config, bed_models, overrides,
            archive_folder=archive_folder,
        )
        results.append({
            "name": " + ".join(names),
            "success": success,
            "message": message,
            "archive_path": str(archive_path) if archive_path else None,
            "stats": stats,
        })
    return results


async def handle_upload_status(request: web.Request) -> web.Response:
    """GET /api/upload/{file_id}/status — poll slicing status."""
    user_id = request["user_id"]
    file_id = request.match_info["file_id"]
    uploads: dict = request.app["uploads"]

    info = uploads.get(file_id)
    if info is None:
        return web.json_response({"error": "upload not found"}, status=404)
    if info["user_id"] != user_id:
        return web.json_response({"error": "forbidden"}, status=403)

    result = info.get("slice_result")
    if result is not None:
        # Flatten single-model results for backwards compatibility
        results = result["results"]
        if len(results) == 1:
            r = results[0]
            return web.json_response({
                "status": "done",
                "success": r["success"],
                "message": r["message"],
                "archive_path": r["archive_path"],
                "stats": r["stats"],
            })
        return web.json_response({"status": "done", "results": results})
    if info.get("slice_task") is not None:
        return web.json_response({"status": "slicing"})
    return web.json_response({"status": "pending"})


async def handle_upload_delete(request: web.Request) -> web.Response:
    """DELETE /api/upload/{file_id} — cleanup an upload."""
    user_id = request["user_id"]
    file_id = request.match_info["file_id"]
    uploads: dict = request.app["uploads"]

    info = uploads.get(file_id)
    if info is None:
        return web.json_response({"error": "upload not found"}, status=404)
    if info["user_id"] != user_id:
        return web.json_response({"error": "forbidden"}, status=403)

    task = info.get("slice_task")
    if task and not task.done():
        task.cancel()

    tmpdir = uploads.pop(file_id).get("tmpdir")
    if tmpdir:
        shutil.rmtree(tmpdir, ignore_errors=True)

    return web.json_response({"status": "deleted"})


async def handle_health(request: web.Request) -> web.Response:
    """GET /api/health — simple health check, no auth required."""
    return web.json_response({"status": "ok", "time": int(time.time())})


@web.middleware
async def auth_middleware(request: web.Request, handler) -> web.Response:
    """Validate Bearer token for all endpoints except health and OPTIONS."""
    if request.method == "OPTIONS" or request.path == "/api/health":
        return await handler(request)

    auth = request.headers.get("Authorization", "")
    if not auth.startswith("Bearer "):
        return web.json_response(
            {"error": "missing or invalid Authorization header"}, status=401,
        )

    token_str = auth[7:]
    tokens: dict = request.app["tokens"]
    user_id = validate_token(tokens, token_str)
    if user_id is None:
        return web.json_response({"error": "invalid or expired token"}, status=401)

    request["user_id"] = user_id
    return await handler(request)


@web.middleware
async def cors_middleware(request: web.Request, handler) -> web.Response:
    """Add CORS headers for the Mini App frontend."""
    if request.method == "OPTIONS":
        response = web.Response()
    else:
        response = await handler(request)

    allowed_origin = request.app.get("cors_origin", "*")
    response.headers["Access-Control-Allow-Origin"] = allowed_origin
    response.headers["Access-Control-Allow-Methods"] = "GET, POST, DELETE, OPTIONS"
    response.headers["Access-Control-Allow-Headers"] = "Authorization, Content-Type"
    return response


@web.middleware
async def logging_middleware(request: web.Request, handler) -> web.Response:
    """Log all incoming requests."""
    start = time.time()
    try:
        response = await handler(request)
        elapsed = (time.time() - start) * 1000
        print(f"[API] {request.method} {request.path} → {response.status} ({elapsed:.0f}ms)", flush=True)
        return response
    except Exception as e:
        elapsed = (time.time() - start) * 1000
        print(f"[API] {request.method} {request.path} → ERROR: {e} ({elapsed:.0f}ms)", flush=True)
        raise


def create_web_app(
    config: Config, user_settings: dict,
    cors_origin: str = "*", save_fn=None,
    starred_keys: set[str] | None = None, save_starred_fn=None,
    tokens: dict | None = None,
) -> web.Application:
    """Create and configure the aiohttp web application."""
    app = web.Application(
        middlewares=[logging_middleware, cors_middleware, auth_middleware],
        client_max_size=MAX_UPLOAD_SIZE,
    )
    app["config"] = config
    app["user_settings"] = user_settings
    app["uploads"] = {}
    app["cors_origin"] = cors_origin
    app["tokens"] = tokens if tokens is not None else {}
    if save_fn:
        app["save_fn"] = save_fn
    if starred_keys is not None:
        app["starred_keys"] = starred_keys
    if save_starred_fn:
        app["save_starred_fn"] = save_starred_fn

    app.router.add_get("/api/health", handle_health)
    app.router.add_get("/api/registry", handle_registry)
    app.router.add_get("/api/settings", handle_get_settings)
    app.router.add_post("/api/settings", handle_post_settings)
    app.router.add_delete("/api/settings", handle_delete_settings)
    app.router.add_get("/api/starred", handle_get_starred)
    app.router.add_post("/api/starred", handle_post_starred)
    app.router.add_post("/api/evaluate", handle_evaluate)
    app.router.add_post("/api/upload", handle_upload)
    app.router.add_get("/api/upload/{file_id}/model", handle_upload_model)
    app.router.add_post("/api/upload/{file_id}/pack", handle_upload_pack)
    app.router.add_post("/api/upload/{file_id}/slice", handle_upload_slice)
    app.router.add_get("/api/upload/{file_id}/status", handle_upload_status)
    app.router.add_delete("/api/upload/{file_id}", handle_upload_delete)

    return app
